### PR TITLE
add draft of vignette

### PR DESCRIPTION
**Pull request by jrosen48**
This is the beginning of a vignette in response to [this issue](https://github.com/LucyMcGowan/tidycode/issues/5). 

@acircleda, would you be able and willing to take a look at this? I think the visualization can and should be improved before we make a PR to the tidycode repository.

### CODE REVIEW

**Comment by acircleda** [comment]
Would a viz like this be good? The code is far more complex but the image is more informative.

image

```
proportion_of_file %>% 
  ggplot(aes(x = reorder(classification, prop), y = prop, fill = file))+
  coord_flip()+
  geom_bar(stat="identity")+
  geom_text(aes(x = reorder(classification, prop), y = prop, group = file, label = paste0(round(prop*100, digits=0), "%")), position = position_stack(), hjust=1)+
  geom_text(
    aes(label = paste0(round(stat(y)*100, digits=0), "%"), group = classification), 
    stat = 'summary', fun.y = sum, hjust=-.5
  )+
  scale_y_continuous(labels=scales::percent_format(), limits=c(0,1.1), breaks=c(0, .2, .4, .6, .8, 1))+
  guides(fill=guide_legend(ncol=1))+
  xlab("Type of Code")+
  ylab("Proportion of Code")+
  theme(legend.position = "bottom")


```

**Comment by jrosen48** [comment]
I like it. Not too complex. I tried to read up on some of Claus Wilke's suggestions for visualizing proportions. Any thoughts on how 10.2 may inform this? What we do seems to be like what is recommended in 10.3. 

https://serialmentor.com/dataviz/visualizing-proportions.html

**Comment by jrosen48** [comment]
Had this as a part of the above but splitting it into another comment. Relatedly, I find the sum of the percentages to be somewhat confusing, since those don't add to 100 - and could simply grow larger as the number of files grows larger. I wonder if calculating the proportion across all files is another part of this vignette (as folks would likely be interested in this, too, if they're analyzing more than one file)?

**Comment by acircleda** [comment]
Good points. I have two solutions: show how to calculate a proportion/per file:
image

This can become quite a large viz if they have many files, but if they have many files, they are likely not trying to analyze on a per-file basis?

```
#### proportion of code per file ####
proportion_of_file %>%
  ggplot()+
  coord_flip()+
  geom_bar(aes(x=0, y=prop, fill=reorder(classification, prop)), stat="identity", size=1)+
  scale_y_continuous(labels=scales::percent_format())+
  facet_wrap(~file, ncol=1)+
  labs(
    title = "Proportion of Code by File",
    y = "Proportion of Code",
    fill = "Classification"
  )+
  theme(
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    strip.text = element_text(hjust=0),
    panel.background = element_blank(),
    strip.background = element_blank(),
    panel.grid.major.x = element_line(color="grey80")
  )
```

These could also be side-by-side bars rather than stacked bars to match the plot below.

**Comment by acircleda** [comment]
Idea 2: Overall proportion:

image

Function:
```
calc_proportion_overall <- function(d) {
  d %>% group_by(classification) %>%
    count() %>% ungroup() %>% mutate(
      prop = prop.table(n)
    )
}


proportion_overall <- calc_proportion_overall(classified_code)
proportion_overall
```

Code:
#### Overall proportion ####

```
proportion_overall %>%
  ggplot()+
  coord_flip()+
  geom_bar(aes(x=reorder(classification, prop), y=1), stat="identity", fill="grey80")+
  geom_bar(aes(x=reorder(classification, prop), y=prop, fill=prop), stat="identity")+
  geom_text(aes(x=reorder(classification, prop), y=prop, label=paste0(round(prop*100, digits=0), "%"), hjust=-.5))+
  scale_y_continuous(labels=scales::percent_format())+
  labs(
    title = "Overall Proportion of Code",
    y = "Proportion of Code",
    x = "Classification"
  )+
  theme(
    panel.background = element_blank(),
    legend.position = "none"
  )
```

**Comment by jrosen48** [comment]
love these both, wow. more in a bit

**Comment by jrosen48** [comment]
just worked on the aspect ratio and also added some minor edits - can you take one last review and then we can submit the PR?

**Comment by acircleda** [comment]
Looks good! Not the best viz, but it seems to work.

**Pull request merged**
